---
-
  hosts: web
  gather_facts: yes
  remote_user: midhat

  roles:
    - common

  vars_files:
    - "{{playbook_dir}}/env_vars/prod.yml"

  post_tasks:
    - include: "{{playbook_dir}}/roles/common/handlers/main.yml"
