version: '3.6'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=uaZEjX9A
      - POSTGRES_PASSWORD=iyIwSICwBnHQ
      - POSTGRES_DB=gaming_overload
    ports:
      - 32768:5432
  web:
    build: .
    command: |
      sh /code/entrypoint.sh
      python /code/manage.py runserver 0.0.0.0:8008
    volumes:
     - .:/code
    ports:
      - 8008:8008
    env_file:
      - ./.env.dev
    depends_on:
      - db

volumes:
  postgres_data:
