# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-10 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_meta_data_like', models.IntegerField(blank=True, null=True)),
                ('item_meta_data_dislike', models.IntegerField(blank=True, null=True)),
                ('item_meta_data_date', models.DateTimeField(auto_now_add=True)),
                ('confess_body', models.TextField(blank=True, max_length=1000)),
                ('confess_class', models.CharField(choices=[('primary', 'primary'), ('success', 'success'), ('warning', 'warning')], default=None, max_length=15, null=True)),
                ('confess_admin_approved', models.BooleanField(default=0)),
                ('confess_user_approved', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'confess',
                'ordering': ['-id'],
            },
        ),
    ]
