# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_username', models.CharField(max_length=100)),
                ('comment_body', models.TextField(max_length=250)),
                ('comment_parent', models.BooleanField(default=0)),
                ('comment_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_related_key', to='core.Comment')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Confess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confess_body', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'confess',
            },
        ),
        migrations.CreateModel(
            name='ItemMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_meta_data_type', models.CharField(choices=[('CONF', 'Confess'), ('COMM', 'Comment')], max_length=4)),
                ('item_meta_data_like', models.IntegerField()),
                ('item_meta_data_dislike', models.IntegerField()),
                ('item_meta_data_date', models.DateTimeField(auto_now_add=True)),
                ('item_meta_data_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_meta_data_comment_key', to='core.Comment')),
                ('item_meta_data_confess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_meta_data_confess_key', to='core.Confess')),
            ],
            options={
                'db_table': 'item_meta_data',
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemmetadata',
            unique_together=set([('item_meta_data_type', 'item_meta_data_confess', 'item_meta_data_comment', 'item_meta_data_like', 'item_meta_data_dislike', 'item_meta_data_date')]),
        ),
    ]
