# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmetadata',
            name='item_meta_data_dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemmetadata',
            name='item_meta_data_like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
