# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-16 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190916_1232'),
        ('vote', '0002_auto_20190916_1232'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confess',
        ),
    ]
