# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190607_1144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemmetadata',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='itemmetadata',
            name='item_meta_data_comment',
        ),
        migrations.RemoveField(
            model_name='itemmetadata',
            name='item_meta_data_confess',
        ),
        migrations.AddField(
            model_name='comment',
            name='item_meta_data_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='item_meta_data_dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='item_meta_data_like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confess',
            name='item_meta_data_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='confess',
            name='item_meta_data_dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confess',
            name='item_meta_data_like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ItemMetaData',
        ),
    ]
