# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190607_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='item_meta_data_date',
            field=models.DateTimeField(auto_now_add=True, default='2019-06-07 16:50:41.255608'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confess',
            name='item_meta_data_date',
            field=models.DateTimeField(auto_now_add=True, default='2019-06-07 16:50:41.255608'),
            preserve_default=False,
        ),
    ]
