# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190607_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='confess',
            name='confess_class',
            field=models.CharField(choices=[('primary', 'primary'), ('success', 'success'), ('warning', 'warning')], default=None, max_length=15, null=True),
        ),
    ]
