# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-24 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_confess_confess_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_removed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='confess',
            name='confess_admin_approved',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='confess',
            name='confess_user_approved',
            field=models.BooleanField(default=0),
        ),
    ]
