# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-25 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190624_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_related_key', to='core.Confess'),
        ),
    ]
