# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-26 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190625_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confess',
            options={'ordering': ['-id']},
        ),
    ]
