# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-26 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190626_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confess',
            options={},
        ),
    ]
