# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-27 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190626_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confess',
            name='confess_body',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
