# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-06 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190627_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_session_token', models.CharField(max_length=250)),
                ('item_is_liked', models.BooleanField(default=1)),
                ('comment_session_self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_session_self_key', to='core.Comment')),
            ],
            options={
                'db_table': 'comment_session',
            },
        ),
        migrations.CreateModel(
            name='ConfessSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_session_token', models.CharField(max_length=250)),
                ('item_is_liked', models.BooleanField(default=1)),
                ('confess_session_self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confess_session_self_key', to='core.Confess')),
            ],
            options={
                'db_table': 'confess_session',
            },
        ),
    ]
