# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-09 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190906_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsession',
            old_name='item_is_liked',
            new_name='vote',
        ),
        migrations.RenameField(
            model_name='commentsession',
            old_name='item_session_token',
            new_name='vote_token',
        ),
        migrations.RenameField(
            model_name='confesssession',
            old_name='item_is_liked',
            new_name='vote',
        ),
        migrations.RenameField(
            model_name='confesssession',
            old_name='item_session_token',
            new_name='vote_token',
        ),
        migrations.AlterUniqueTogether(
            name='commentsession',
            unique_together=set([('comment_session_self', 'vote_token')]),
        ),
        migrations.AlterUniqueTogether(
            name='confesssession',
            unique_together=set([('confess_session_self', 'vote_token')]),
        ),
    ]
