# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190909_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfessVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_token', models.CharField(max_length=250)),
                ('vote', models.BooleanField(default=1)),
                ('confess_vote_self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confess_vote_self_key', to='core.Confess')),
            ],
            options={
                'db_table': 'confess_vote',
            },
        ),
        migrations.AlterUniqueTogether(
            name='confesssession',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='confesssession',
            name='confess_session_self',
        ),
        migrations.DeleteModel(
            name='ConfessSession',
        ),
        migrations.AlterUniqueTogether(
            name='confessvote',
            unique_together=set([('confess_vote_self', 'vote_token')]),
        ),
    ]
