# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-09 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190909_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_token', models.CharField(max_length=250)),
                ('vote', models.BooleanField(default=1)),
                ('comment_vote_self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_vote_self_key', to='core.Comment')),
            ],
            options={
                'db_table': 'comment_vote',
            },
        ),
        migrations.AlterUniqueTogether(
            name='commentsession',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='commentsession',
            name='comment_session_self',
        ),
        migrations.DeleteModel(
            name='CommentSession',
        ),
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set([('comment_vote_self', 'vote_token')]),
        ),
    ]
