# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-09 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190909_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='commentvote',
            name='comment_vote_self',
        ),
        migrations.AlterUniqueTogether(
            name='confessvote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='confessvote',
            name='confess_vote_self',
        ),
        migrations.DeleteModel(
            name='CommentVote',
        ),
        migrations.DeleteModel(
            name='ConfessVote',
        ),
    ]
