---

- name: Create app folder
  file:
    path: "{{app_path}}"
    state: directory
    mode: '0755'

- name: Check docker-compose.yml
  stat:
    path: "{{compose_file_path}}"
  register: compose_file_output

- name: Docker-compose down
  docker_compose:
    project_src: "{{app_path}}"
    state: absent
    timeout: 300
  when: compose_file_output.stat.exists == true

- name: Update Docker-compose file
  template:
    src: "{{ source_comppose_file | default('docker-compose.yml') }}"
    dest: "{{compose_file_path}}"