# Generated by Django 2.2.6 on 2019-11-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def insert_data(self, apps, schema):
        Rule = apps.get_model("rule", "Rule")
        new_rule = Rule(name="Approve confession", app="confession", model="Confession", value=50)
        new_rule.save()

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('app', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.RunPython(insert_data),
    ]
