# Generated by Django 2.2.8 on 2019-12-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0003_rule_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
