version: 2.1
executors:
      docker-publisher:
        environment:
          IMAGE_NAME: midhatstam/konfess
        docker:
          - image: circleci/buildpack-deps:stretch
jobs:
  build-job:
    docker:
      - image: circleci/python:3.6.8
      - image: circleci/postgres:12.0
    environment:
      DATABASE_URL: postgres://postgres:@localhost/circle_test
      DJANGO_SECRET_KEY: ef+-3suc6+7wh%-n1hr71v83-5wvu7)dl8au#w9fe@4jd-af3#
      DJANGO_READ_DOT_ENV_FILE: True
      DJANGO_SETTINGS_MODULE: confess.settings
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache:
          key: v001-code-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v001-code-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
      - run:
          name: Migrate
          command: |
            . venv/bin/activate
            python manage.py migrate
      - run:
          name: Static analysis
          command: |
            . venv/bin/activate
            pip install pylint flake8
            pylint ./ --output-format=parseable --exit-zero > pylint.log
            flake8 ./ --format=pylint --exit-zero > flake8.log
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            tox
  server-deploy:
    docker:
      - image: circleci/buildpack-deps:18.04
    working_directory: ~/code
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "91:f8:f0:a0:68:de:00:29:2c:41:72:7f:54:f8:dc:d9"
      - run:
          name: Install Ansible
          command: |
            sudo apt update -y
            sudo apt install -y software-properties-common
            sudo apt-add-repository -y ppa:ansible/ansible
            sudo apt update -y
            sudo apt install -y ansible
      - run:
          name: Run ansible playbook
          command: |
            ansible-playbook -i .circleci/hosts .circleci/ansible/deploy.yml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - server-deploy:
          requires:
            - build-job
          filters:
            branches:
              only:
                - develop
