version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:3.8.0
      - image: circleci/postgres:12.0
    environment:
      DATABASE_URL: postgres://postgres:@localhost/circle_test
      DJANGO_SECRET_KEY: ef+-3suc6+7wh%-n1hr71v83-5wvu7)dl8au#w9fe@4jd-af3#
      DJANGO_READ_DOT_ENV_FILE: True
      DJANGO_SETTINGS_MODULE: confess.settings
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache:
          key: v001-code-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: v001-code-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - 'venv'
      - run:
          name: Migrate
          command: |
            . venv/bin/activate
            python manage.py migrate
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test
  deploy-job:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  server-deploy-job:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Deploy via Fabric
          command: |
            sudo pip install fabric==1.14.0
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              fab -f .circleci/deploy.py -i ~/.ssh/github_rsa production deploy
            else
              fab -f .circleci/deploy.py -i ~/.ssh/github_rsa staging deploy
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only:
                - develop
      - server-deploy-job:
          requires:
            - deploy-job
          filters:
            branches:
              only:
               master
#      - deploy-job:
#          requires:
#            - build-job
#          filters:
#            branches:
#              only:
#                - develop
#                - master
