#- name: restart postgres
#  service: name=postgresql state=restarted
#  become: true
#  become_method: sudo

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  become: true
  become_method: sudo

- name: restart gunicorn
  service: name=gunicorn state=restarted
  become: true
  become_method: sudo

- name: restart supervisor
  service: name=supervisor state=restarted
  become: true
  become_method: sudo
