# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_auto_20190909_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_token', models.CharField(max_length=250)),
                ('vote', models.BooleanField(default=1)),
                ('comment_vote_self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_vote_self_key', to='core.Comment')),
            ],
            options={
                'db_table': 'comment_vote',
            },
        ),
        migrations.CreateModel(
            name='ConfessVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_token', models.CharField(max_length=250)),
                ('vote', models.BooleanField(default=1)),
                ('confess_vote_self', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confess_vote_self_key', to='core.Confess')),
            ],
            options={
                'db_table': 'confess_vote',
            },
        ),
        migrations.AlterUniqueTogether(
            name='confessvote',
            unique_together=set([('confess_vote_self', 'vote_token')]),
        ),
        migrations.AlterUniqueTogether(
            name='commentvote',
            unique_together=set([('comment_vote_self', 'vote_token')]),
        ),
    ]
