# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-17 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20190917_1201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
