# Generated by Django 2.2.6 on 2019-10-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_meta_data_date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True, max_length=1000)),
                ('css_class', models.CharField(choices=[('primary', 'primary'), ('success', 'success'), ('warning', 'warning')], default=None, max_length=15, null=True)),
                ('admin_approved', models.BooleanField(default=0)),
                ('user_approved', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'confession',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedConfession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('confession.confession',),
        ),
    ]
