# Generated by Django 2.2.6 on 2019-10-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='reported',
            field=models.BooleanField(default=0),
        ),
    ]
