# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-19 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedConfession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('confession.confession',),
        ),
    ]
