# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-20 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0002_approvedconfession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confession',
            name='item_meta_data_dislike',
        ),
        migrations.RemoveField(
            model_name='confession',
            name='item_meta_data_like',
        ),
    ]
