# Generated by Django 2.2.6 on 2019-10-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0002_confession_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApprovedConfession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('confession.confession',),
        ),
        migrations.CreateModel(
            name='AllConfession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('confession.confession',),
        ),
        migrations.CreateModel(
            name='ReportedConfession',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('confession.confession',),
        ),
    ]
