# Generated by Django 2.2.7 on 2019-11-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0005_confessionforapprove'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfessionUserApprovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_meta_data_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('vote', models.IntegerField(default=1)),
                ('token', models.CharField(max_length=250)),
                ('confession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confession.Confession')),
            ],
            options={
                'db_table': 'confession_user_approvement',
            },
        ),
    ]
