# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-17 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('vote_token', 'content_type')]),
        ),
    ]
