# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-17 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20190917_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(default=1),
        ),
    ]
