# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-19 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('voting', '0003_auto_20190917_1459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('vote_token', 'content_type', 'object_id')]),
        ),
    ]
