# Generated by Django 2.2.6 on 2019-11-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomment',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
