version: "3.5"
services:
  web:
    build: .
    command: |
      sh /confess/entrypoint.sh
      python /confess/manage.py runserver 0.0.0.0:8000
    volumes:
     - .:/confess
    ports:
      - 8000:8000
    env_file:
      - ./.env
#  nginx:
#    image: {{docker_nginx_image}}
#    ports:
#      - "80:80"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - /tmp/statics:/web:ro
#    restart: always
#    tty: true
#    logging:
#      options:
#        max-size: 100m
