# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-15 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('confession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_meta_data_like', models.PositiveIntegerField(default=0)),
                ('item_meta_data_dislike', models.PositiveIntegerField(default=0)),
                ('item_meta_data_date', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField()),
                ('is_parent', models.BooleanField(default=1)),
                ('removed', models.BooleanField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_related_key', to='confession.Confession')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
