# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-10 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_meta_data_like', models.IntegerField(blank=True, null=True)),
                ('item_meta_data_dislike', models.IntegerField(blank=True, null=True)),
                ('item_meta_data_date', models.DateTimeField(auto_now_add=True)),
                ('comment_username', models.CharField(max_length=100)),
                ('comment_body', models.TextField(max_length=250)),
                ('comment_parent', models.BooleanField(default=0)),
                ('comment_removed', models.BooleanField(default=0)),
                ('comment_related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_related_key', to='core.Confess')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
