# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='item_meta_data_dislike',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='item_meta_data_like',
        ),
        migrations.AlterField(
            model_name='comment',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='confession.Confession'),
        ),
    ]
