# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-16 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confession', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_parent',
            new_name='removed',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_related',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_removed',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_username',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_parent',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_related_key', to='confession.Confession'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item_meta_data_dislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item_meta_data_like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
