name: Create pull request

on:
  push:
    branches: 
      - "feature/*"

jobs:
  pull request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@develop
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: ":crown: *An automated PR*"
        github_token: ${{ secrets.GITHUB_TOKEN }}
